### PR TITLE
Fix xp command showing next level

### PR DESCRIPTION
**Pull request by dkim19375**
Did this on phone so idk if I missed a spot and I couldn't test

I'd recommend renaming the method or make it all +1, but I'm on phone so I'm too lazy to do all that

### CODE REVIEW

**Review by lucypoulton — APPROVED** [review]
i could've sworn these were +1 already, i remember putting it in

**Comment by dkim19375** [comment]
> i could've sworn these were +1 already, i remember putting it in

They were, but that function returns the xp needed for the next level (didn't check that function code but that's how the leveling detection system worked), so a +1 would check the next next level xp

**Comment by dkim19375** [comment]
okay wepl

**Comment by dkim19375** [comment]
welp*

**Comment by knightzmc** [comment]
lol

**Pull request closed without merging**
